<?php

namespace app\admin\controller;

use think\Lang;
/**
 * ============================================================================
 *在线教育培训付费视频管理系统
 * ============================================================================
 * 版权所有 重庆师范大学计算机科学与技术杨玉印，并保留所有权利。
 * 网站地址: http://yyu.loveli.top

 * ============================================================================
 * 控制器
 */
class Feedback extends AdminControl
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        Lang::load(APP_PATH . 'admin/lang/'.config('default_lang').'/feedback.lang.php');
    }
    /**
     * 意见反馈
     */
    public function flist(){
        $feedback_model = model('feedback');
        $feedback_list = $feedback_model->getFeedbackList(array(), 10);

       $this->assign('feedback_list', $feedback_list);
       $this->assign('show_page', $feedback_model->page_info->render());
       $this->setAdminCurItem('index');
       return $this->fetch('index');
    }

    /**
     * 删除
     */
    public function del(){
        $feedback_model = model('feedback');
        $feedback_id = input('param.feedback_id');
        $feedback_id_array = ds_delete_param($feedback_id);
        $condition = array('fb_id' => array('in', $feedback_id_array));
        $result = $feedback_model->delFeedback($condition);
        if ($result){
            ds_json_encode(10000, lang('ds_common_op_succ'));
        }else {
            ds_json_encode(10001, lang('ds_common_op_fail'));
        }
    }
    protected function getAdminItemList() {
        $menu = array(
            array(
                'text' => lang('ds_feedback'), 'name' => 'index', 'url' => ''
            ),
        );
        return $menu;
    }
}